// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/xu756/qmcy/app/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/getGroups",
					Handler: GetGroupsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/app/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/getContents",
					Handler: GetContentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getContent",
					Handler: GetContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/addContent",
					Handler: AddContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/editContent",
					Handler: EditContentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delContent",
					Handler: DelContentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/app/admin/mini"),
	)
}
