// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package admin

import (
	"context"
	"github.com/xu756/qmcy/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGroupReq   = pb.GetGroupReq
	Group         = pb.Group
	GroupList     = pb.GroupList
	GroupUserInfo = pb.GroupUserInfo

	Admin interface {
		GetGroups(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GroupList, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) GetGroups(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GroupList, error) {
	client := pb.NewAdminClient(m.cli.Conn())
	return client.GetGroups(ctx, in, opts...)
}
