// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roleFieldNames          = builder.RawFieldNames(&Role{}, true)
	roleRows                = strings.Join(roleFieldNames, ",")
	roleRowsExpectAutoSet   = strings.Join(stringx.Remove(roleFieldNames), ",")
	roleRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(roleFieldNames, "id"))

	cachePublicRoleIdPrefix = "cache:public:role:id:"
)

type (
	roleModel interface {
		Insert(ctx context.Context, data *Role) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Role, error)
		Update(ctx context.Context, data *Role) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRoleModel struct {
		sqlc.CachedConn
		table string
	}

	Role struct {
		Id       int64  `db:"id"`        // 角色ID
		ParentId int64  `db:"parent_id"` // 所属父级角色ID
		Code     string `db:"code"`      // 角色唯一CODE代码
		Name     string `db:"name"`      // 角色名称
		Intro    string `db:"intro"`     // 角色介绍
		Created  int64  `db:"created"`   // 创建时间
		Creator  int64  `db:"creator"`   // 创建人
		Edited   int64  `db:"edited"`    // 修改时间
		Editor   int64  `db:"editor"`    // 修改人
		Deleted  int64  `db:"deleted"`   // 逻辑删除:0=未删除,1=已删除
	}
)

func newRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRoleModel {
	return &defaultRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."role"`,
	}
}

func (m *defaultRoleModel) withSession(session sqlx.Session) *defaultRoleModel {
	return &defaultRoleModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      `"public"."role"`,
	}
}

func (m *defaultRoleModel) Delete(ctx context.Context, id int64) error {
	publicRoleIdKey := fmt.Sprintf("%s%v", cachePublicRoleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicRoleIdKey)
	return err
}

func (m *defaultRoleModel) FindOne(ctx context.Context, id int64) (*Role, error) {
	publicRoleIdKey := fmt.Sprintf("%s%v", cachePublicRoleIdPrefix, id)
	var resp Role
	err := m.QueryRowCtx(ctx, &resp, publicRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", roleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleModel) Insert(ctx context.Context, data *Role) (sql.Result, error) {
	publicRoleIdKey := fmt.Sprintf("%s%v", cachePublicRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, roleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ParentId, data.Code, data.Name, data.Intro, data.Created, data.Creator, data.Edited, data.Editor, data.Deleted)
	}, publicRoleIdKey)
	return ret, err
}

func (m *defaultRoleModel) Update(ctx context.Context, data *Role) error {
	publicRoleIdKey := fmt.Sprintf("%s%v", cachePublicRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, roleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.ParentId, data.Code, data.Name, data.Intro, data.Created, data.Creator, data.Edited, data.Editor, data.Deleted)
	}, publicRoleIdKey)
	return err
}

func (m *defaultRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicRoleIdPrefix, primary)
}

func (m *defaultRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", roleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRoleModel) tableName() string {
	return m.table
}
