// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"
	"github.com/xu756/qmcy/pb"

	"github.com/xu756/qmcy/app/admin/rpc/internal/logic"
	"github.com/xu756/qmcy/app/admin/rpc/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServer) GetGroups(ctx context.Context, in *pb.GetGroupReq) (*pb.GroupList, error) {
	l := logic.NewGetGroupsLogic(ctx, s.svcCtx)
	return l.GetGroups(in)
}
