// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"
	"github.com/xu756/qmcy/pb"

	"github.com/xu756/qmcy/app/admin/rpc/internal/logic"
	"github.com/xu756/qmcy/app/admin/rpc/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServer) GetGroups(ctx context.Context, in *pb.GetGroupReq) (*pb.GroupList, error) {
	l := logic.NewGetGroupsLogic(ctx, s.svcCtx)
	return l.GetGroups(in)
}

func (s *AdminServer) GetContent(ctx context.Context, in *pb.ContentReq) (*pb.Content, error) {
	l := logic.NewGetContentLogic(ctx, s.svcCtx)
	return l.GetContent(in)
}

func (s *AdminServer) GetContents(ctx context.Context, in *pb.ContentsReq) (*pb.ContentList, error) {
	l := logic.NewGetContentsLogic(ctx, s.svcCtx)
	return l.GetContents(in)
}

func (s *AdminServer) AddContent(ctx context.Context, in *pb.Content) (*pb.Ok, error) {
	l := logic.NewAddContentLogic(ctx, s.svcCtx)
	return l.AddContent(in)
}

func (s *AdminServer) EditContent(ctx context.Context, in *pb.Content) (*pb.Ok, error) {
	l := logic.NewEditContentLogic(ctx, s.svcCtx)
	return l.EditContent(in)
}

func (s *AdminServer) DelContent(ctx context.Context, in *pb.ContentReq) (*pb.Ok, error) {
	l := logic.NewDelContentLogic(ctx, s.svcCtx)
	return l.DelContent(in)
}
