// Code generated by goctl. DO NOT EDIT.
package types

type Empty struct {
}

type UserInfo struct {
	Id        int64   `json:"id" desc:"用户id"`
	Name      string  `json:"name" desc:"用户名称"`
	Avatar    string  `json:"avatar" desc:"用户头像"`
	Role      []int64 `json:"role" desc:"用户角色"`
	GroupCode string  `json:"group_code" desc:"用户组"`
}
